name: Main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  workflow_call:
jobs:
  runs-on: ubuntu-latest

  setup:
    uses: fayaz07/gh-actions/.github/workflows/setup.yml@main

  build:
    needs: setup
    steps:
      - uses: actions/checkout@v3

      - name: Say Main
        run: echo "Main"
