name: Setup

# Controls when the workflow will run
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: bash src/hello.sh
